site_name: My Docs
site_description: Site do projeto de Engenharia de Dados da SATC
site_author: Jorge Luiz da Silva
site_url: https://jlsilva01.github.io/projeto-ed-satc
site_favicon: images/favicon.png
site_logo: images/logo.png
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

repo_name: projeto-ed-satc
repo_url: http://github.com/jlsilva01/projeto-ed-satc
edit_uri: edit/master/docs/

docs_dir: docs

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  palette:
    primary: purple
  language: pt

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python